version: "3"

services:

  cdot-rest:
    image: cdot-rest:dev
    build:
      context: .
    command: bash -c "gunicorn cdot_rest.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - settings/.env.dev
    depends_on:
      - redis
    ports:
      - "8002:8000"

  redis:
    image: redis:7.2.3
    env_file:
      - settings/.env.dev
    ports:
      - "6381:6379"
    volumes:
      - cdot-redis-dev:/data



volumes:
  cdot-redis-dev:
